### ISSUE TITLE
23.247.128.0/17 (inclusive of our IP block 23.247.208.0/22) Listed Incorrectly as Web Server Service

### ISSUE THREAD

**Issue by rcoulsell** [pushinginertia/ip-blacklist#11]
Ref: https://github.com/firehol/blocklist-ipsets/issues/199

The IP block 23.247.208.0/22 was recently acquired through an ARIN Direct Allocation by FiberFly, LLC.
This can be verified via: https://search.arin.net/rdap/?query=23.247.208.0%2F22
FiberFly is a rural internet service provider (ISP), serving parts of Waxahachie, TX in the USA.
This can be verified at: https://fiberfly.com

We do not perform hosting services. We only provide home and business internet connections to our rural community.
Apparently the previously identified entity (micfo.com) was a hosting company, hence this block being included in your list.

Please update to remove this block from your list 'ip_blacklist.conf' on row 1209.

Row 1209: Remove '23.247.128.0/17'

This /17 block was been split among numerous organizations through ARIN via Direct Allocation in or around Oct 2021:
23.247.128.0/22 - IDC SPACE INC
23.247.132.0/22 - BRAIN PEACE SCIENCE FOUNDATION, INC
23.247.136.0/22 - Black Mesa Corporation
23.247.140.0/22 - Sky Fi
23.247.144.0/22 - VPB INC.
23.247.148.0/22 - City of Marshall
23.247.152.0/22 - VPSie INC
23.247.156.0/22<-- Not Assigned by ARIN
23.247.160.0/22 - One
23.247.164.0/22 - I.D. Logique
23.247.168.0/22 - Nasulex Networks
23.247.172.0/22 - Optelli Fiber LLC
23.247.176.0/22 - SDWANET LLC
23.247.180.0/24 - Ridge Wireless LLC
23.247.184.0/23 - PeopleHedge Corp
23.247.188.0/23 - Raptor Engineering, LLC
23.247.192.0/22 - I.S.F Quebec, Inc
23.247.196.0/22 - Clearwave Broadband Networks Inc.
23.247.200.0/22 - GHOST CLOUD LLC
23.247.204.0/22 - Estherville Communications LLC
23.247.208.0/22 - fiberfly <<<--------------------------------------------------------This is us!!!
23.247.212.0/22 - nextdns, Inc.
23.247.216.0/22 - City of Sylvester
23.247.220.0/22 - Data Stream
23.247.224.0/22 - BluBroadband ISP
23.247.228.0/22 - Kingsburg Media Foundation
23.247.232.0/22 - Voxtelesys LLC
23.247.236.0/22 - campuscolo.com
23.247.240.0/22 - Fortlab
23.247.244.0/22 - David & Denis Inc.
23.247.248.0/24 - RCG Communications, LLC
23.247.249.0/24 - Jackson County Memorial Hospital
23.247.250.0/23 - G5 INTERNET, LLC
23.247.252.0/24 - Computer Marketing Corporation
23.247.253.0/24 - Madon Damien, Sole Proprietorship
23.247.254.0/23 - HARRIS COUNTY TOLL ROAD AUTHORITY

**Comment by pushinginertia** [comment]
Thanks @rcoulsell, that's now removed.

**Comment by rcoulsell** [comment]
Thank you @pushinginertia !!!
