### ISSUE TITLE
apache 2.4.10 on debian jessie

### ISSUE THREAD

**Issue by latimeria68** [pushinginertia/ip-blacklist#5]
Hello,
can someone please explain me how to use ip-blacklist.conf with apache 2.4.10 on debian jessie?
Thanks

**Comment by davicrystal** [comment]
Hi,

1-) Put the file ip_blacklist.conf in the /etc/apache2/conf-avaliable folder

2-) Execute: `$ sudo a2enconf ip_blacklist.conf` 

3-) Check out if everything is ok:  `$ sudo apachectl configtest`

4-) Reload Apache: `$ sudo service apache2 reload`

**Comment by latimeria68** [comment]
Hi,
many thanks! do you think the `order allow,deny` instruction in ip_blacklist.conf file should be replaced by `Require all granted` as apache version is 2.4 and the sintax seems to have been changed?

**Comment by latimeria68** [comment]
just made a test denying the ip address of one machine on my local network and it works even with apache 2.2 sintax.
Thanks again
